# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: amazingzcj
subtitle: Be amazing with ZCJ.
description: Make great efforts, meanwhile, Enjoy life and love~!
keywords: javascript,html,css,react,npm,git
author: ZCJ
language: zh-CN
  # - zh-Hans
  # - en
timezone:

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://amazingzcj.github.io
root: /
# permalink: :year/:month/:day/:title/
permalink: :title.html
permalink_defaults:
  lang: en

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :year-:i_month-:day-:title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  # enable: true
  # line_number: true
  # auto_detect: false
  # tab_replace:
  
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 12
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/

# theme: next
theme: hexo-theme-matery

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git
  repo: https://github.com/amazingzcj/amazingzcj.github.io.git
  branch: master

# 自定义
# hexo-prism-plugin
## 代码高亮
prism_plugin:
  mode: 'preprocess'    # realtime/preprocess
  theme: 'atom-dark'
  line_number: false    # default false
  custom_css:
    
# hexo-generator-search
## 内容搜索
search:
  path: search.xml
  field: post

# hexo-permalink-pinyin
## 中文链接转拼音
permalink_pinyin:
  enable: true
  separator: '-' # default: '-'

# hexo-generator-feed 
## RSS订阅
feed:
  type: atom
  path: atom.xml
  limit: 20
  hub:
  content:
  content_limit: 140
  content_limit_delim: ' '
  order_by: -date

# 看板娘
live2d:
  enable: false
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: live2d-widget-model-hijiki
    scale: 1
    hHeadPos: 0.5
    vHeadPos: 0.618
  display:
    superSample: 2
    position: left
    width: 200
    height: 400
    hOffset: 0
    vOffset: 10
  mobile:
    show: false
    scale: 0.2
  react:
    opacityDefault: 0.5
    opacityOnHover: 0.1
